server:
  port: 0

spring:
  r2dbc:
    url: r2dbc:postgresql://containers-us-west-12.railway.app:7398/railway
    username: postgres
    password: guYuOD5jSHl7WCFcoZUu
    pool:
      enabled: true
      initial-size: 1
      max-size: 1
  application:
    name: programs-microservice



logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
